name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: [self-hosted, ghfar]
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodby cruel World"
